Тищенко Олеся, SE 6, hometask 3
lesya-tishencko/scala-2017 pull request #2
Opened 2017-09-25 08:23 UTC by lesya-tishencko

2017-09-25 08:55 UTC, adkozlov commented
Добавьте, пожалуйста, @dzharkov в качестве ревьюера.

2017-09-25 08:58 UTC, adkozlov commented
Добавьте, пожалуйста, @dovchinnikov в качестве ревьюера.

2017-10-07 20:10 UTC, adkozlov commented
Ping, @lesya-tishencko.

2017-10-14 12:19 UTC, dzharkov requested changes
Жду исправлений и ответов на вопросы 17.10 23:59. Не забудь написать “@dzharkov” в комменте к PR

2017-10-14 12:19 UTC, dzharkov commented on src/main/scala/ru/spbau/jvm/scala/WeatherBot.scala
> +  val map: mutable.HashMap[Long, String] = mutable.HashMap.empty
Из названия и типов мапы ничего не ясно совсем :(

2017-10-14 12:19 UTC, dzharkov commented on src/main/scala/ru/spbau/jvm/scala/WeatherBot.scala
> +  val map: mutable.HashMap[Long, String] = mutable.HashMap.empty
Советую обратить внимание на тайп алиасы в скале

2017-10-14 12:19 UTC, dzharkov commented on src/main/scala/ru/spbau/jvm/scala/WeatherBot.scala
> +              implicit val timeout: Timeout = Timeout(1.second)
Очень тяжело читать реализацию всего бота в одной функции
-1

2017-10-14 12:19 UTC, dzharkov commented on src/main/scala/ru/spbau/jvm/scala/WeatherActor.scala
> +  val mapCity: mutable.HashMap[String, (Long, String)] = mutable.HashMap.empty
Тоже самое с именами и типами здесь

2017-10-14 12:19 UTC, dzharkov commented on src/main/scala/ru/spbau/jvm/scala/WeatherActor.scala
> +  val queryString = "http://api.openweathermap.org/data/2.5/weather?appid=4ca042807dbef1d736b5a0a79ffee657&q="
https://docs.scala-lang.org/style/naming-conventions.html
Имена для констант должны начинаться с заглавной буквы

2017-10-14 12:19 UTC, dzharkov commented on src/main/scala/ru/spbau/jvm/scala/WeatherBot.scala
> +                  if (System.currentTimeMillis() - time.asInstanceOf[Long] > 600000)
Предлагаю создать для кэширования отдельный класс

2018-01-26 00:49 UTC, lesya-tishencko commented
@dzharkov У меня в табличке за это задание не стоит балл, я подозреваю, что из-за того, что я в свое время не отправила изменения. Я сделала запрашиваемые изменения и очень надеюсь, что еще не поздно их предоставить.

2018-01-26 06:32 UTC, dzharkov commented
Ок, 9/10

2018-01-26 06:32 UTC, closed without merging