Тищенко Олеся, SE 6, hometask 4
lesya-tishencko/scala-2017 pull request #3
Opened 2017-10-02 00:50 UTC by lesya-tishencko

2017-10-23 12:12 UTC, adkozlov requested changes
Достаточно много замечаний.
Не только мелких стилистических, но и по проектированию.
Еще сильно расстраивает тот факт, что полностью игнорируются инспекции -- во многих местах IntelliJ IDEA подсказывает исправления.

2017-10-23 12:12 UTC, adkozlov commented on src/test/scala/ru/sbau/jvm/scala/MultiSetTest.scala
> +    assert(mySet.apply(1) == 1)
В Scala не принято вызывать `apply` явно.

2017-10-23 12:12 UTC, adkozlov commented on src/test/scala/ru/sbau/jvm/scala/MultiSetTest.scala
> +    assert(mySet.apply(1) == 1)
Также лучше пользоваться более специфичными методами: `assertEquals`, `assertNotNull` и т.д.

2017-10-23 12:12 UTC, adkozlov commented on src/test/scala/ru/sbau/jvm/scala/MultiSetTest.scala
> +    assert(!mySet.contains(2))
`assertFalse`, например.

2017-10-23 12:12 UTC, adkozlov commented on src/test/scala/ru/sbau/jvm/scala/MultiSetTest.scala
> +    mySet + 1;
Точки с запятой.

2017-10-23 12:12 UTC, adkozlov commented on src/test/scala/ru/sbau/jvm/scala/MultiSetTest.scala
> +      case _ => assert(false)
`assert(false)` эквивалентно `fail()`.

2017-10-23 12:12 UTC, adkozlov commented on src/test/scala/ru/sbau/jvm/scala/MultiSetTest.scala
> +    filtred.apply(2) match {
Не совсем понятно, зачем здесь делать такой паттерн-матчинг.
Это ведь просто `assert(filtered.apply(2) == 2)`.

2017-10-23 12:12 UTC, adkozlov commented on src/test/scala/ru/sbau/jvm/scala/MultiSetTest.scala
> +    val filtred = mySet.filter(x => x < 3)
`filtered`. Эту опечатку даже IntelliJ IDEA подсказывает.

2017-10-23 12:12 UTC, adkozlov commented on src/test/scala/ru/sbau/jvm/scala/MultiSetTest.scala
> +    assert(mySet.find("1_one") == Some("1_one"))
Здесь тоже инспекция. Можно заменить на вызов `contains`.

2017-10-23 12:12 UTC, adkozlov commented on src/test/scala/ru/sbau/jvm/scala/MultiSetTest.scala
> +    assert(mySet.find("") == None)
Инспекция. Лучше использовать `isEmpty`.

2017-10-23 12:12 UTC, adkozlov commented on src/test/scala/ru/sbau/jvm/scala/MultiSetTest.scala
> +      if (res == Some(20))
Непонятный `if`. Эквивалентно: `assert(res == Some(20))`.

2017-10-23 12:12 UTC, adkozlov commented on src/main/scala/ru/sbau/jvm/scala/MultiSet.scala
> +package ru.spbau.jvm.scala
Путь к файлу не соответствует имени пакета. Warning.

2017-10-23 12:12 UTC, adkozlov commented on src/main/scala/ru/sbau/jvm/scala/MultiSet.scala
> +  def apply[A](map: Map[A, Int] = Map.empty): MultiSet[A] = new MultiSet(map)
`apply` в companion object предполагает конструирование коллекции от набора элементов.
Чтобы можно было писать так: `MultiSet(1, 2, 2, 3)`.

2017-10-23 12:12 UTC, adkozlov commented on src/main/scala/ru/sbau/jvm/scala/MultiSet.scala
> +      Some(arg.map.foldLeft(Seq.empty[A])((arg, next) => arg ++ Seq.fill(next._2)(next._1)))
Лучше заименовывать поля кортежей.
Плюс имя `arg` уже занято.
```scala
Some(map.foldLeft(Seq.empty[A]) {
      case (arg, (element, count)) => arg ++ Seq.fill(count)(element)
})
```

2017-10-23 12:12 UTC, adkozlov commented on src/main/scala/ru/sbau/jvm/scala/MultiSet.scala
> +    if (arg.map.isEmpty) None else
`arg.map` вызывается в обеих ветках.

2017-10-23 12:12 UTC, adkozlov commented on src/main/scala/ru/sbau/jvm/scala/MultiSet.scala
> +class MultiSet[A](private var map: Map[A, Int] = Map.empty[A, Int]) {
`map` -- не самое содержательное название, тем более оно еще и приводит к коллизиям.
Имя `elements` подходило бы больше.

В данном случае не обязательно указывать явно параметры типа: `Map.empty`.

`equals`, `hashCode`, `toString`? Коллекции хотелось бы уметь сравнивать между собой.

2017-10-23 12:12 UTC, adkozlov commented on src/main/scala/ru/sbau/jvm/scala/MultiSet.scala
> +  def +(elem: A): Unit = this.map = this.map + (elem -> (this.map.getOrElse(elem, 0) + 1))
1) Методы, возвращающие `Unit` (с сайд-эффектами) не принято записывать без скобок.
2) Раз уж у вас коллекция изменяемая, то хранить внутреннее состояние гораздо удобнее в `mutable.Map`. Тогда этот метод выглядел бы так:
```scala
elements += (elem -> this(elem) + 1)
```
`this(elem)` эквивалентно `apply(elem), которое и есть `elements.getOrElse(elem, 0)`. То есть тут дубликация кода имеется.

2017-10-23 12:12 UTC, adkozlov commented on src/main/scala/ru/sbau/jvm/scala/MultiSet.scala
> +    case None => ()
Литерал `()` не нужно возвращать явно.

2017-10-23 12:12 UTC, adkozlov commented on src/main/scala/ru/sbau/jvm/scala/MultiSet.scala
> +    case Some(1) => this.map = this.map - elem
Опять же, при использовании изменяемой коллекции: `elements -= elem`.

2017-10-23 12:12 UTC, adkozlov commented on src/main/scala/ru/sbau/jvm/scala/MultiSet.scala
> +  def -(elem: A): Unit = this.map.get(elem) match {
Мне обычно не очень понятно, зачем эти вот сокращения: `elem` вместо `element`?

2017-10-23 12:12 UTC, adkozlov commented on src/main/scala/ru/sbau/jvm/scala/MultiSet.scala
> +    case Some(n) => this.map = this.map + (elem -> (n - 1))
`elements += (elem -> (n - 1)`

2017-10-23 12:12 UTC, adkozlov commented on src/main/scala/ru/sbau/jvm/scala/MultiSet.scala
> +  def find(elem: A): Option[A] = this.map.get(elem) match {
По сути этот метод -- проверка `contains` и оборачивание элемента в `Option`.
Если это очень нужно (обычно нет), можно объявить такой метод. Однако он может быть выражен с помощью публичного интерфейса класса и объявлен в качестве утильного.

2017-10-23 12:12 UTC, adkozlov commented on src/main/scala/ru/sbau/jvm/scala/MultiSet.scala
> +  def map[B](fun: A => B): MultiSet[B] = new MultiSet(this.map.map(x => (fun(x._1) -> x._2)))
По синтаксису. Достаточно сложно читаемая запись.
Что можно сделать:
```scala
val newElements = elements.map {
      case (element, count) => fun(element) -> count
}
new MultiSet(newElements)
```

2017-10-23 12:12 UTC, adkozlov commented on src/main/scala/ru/sbau/jvm/scala/MultiSet.scala
> +  def map[B](fun: A => B): MultiSet[B] = new MultiSet(this.map.map(x => (fun(x._1) -> x._2)))
Но основная проблема в том, что метод работает неправильно.
Что будет, если мы передадим функцию: `_ => 0`?

2017-10-23 12:12 UTC, adkozlov commented on src/main/scala/ru/sbau/jvm/scala/MultiSet.scala
> +      case Some(n) => (x._1, min(x._2, n))
`n.min(x._2)`

2017-10-23 12:12 UTC, adkozlov commented on src/main/scala/ru/sbau/jvm/scala/MultiSet.scala
> +      case None => (x._1, -1)
Можно заметить, что `x._1` возвращается в любом случае. То есть этот паттерн-матчинг отвечает только за новое `Int` значение.

2017-10-23 12:12 UTC, adkozlov commented on src/main/scala/ru/sbau/jvm/scala/MultiSet.scala
> +    var sumMap = other.map.map(x => (x._1, x._2 + this.map.getOrElse(x._1, 0)))
Этот метод какой-то совсем нечитаемый.
Поможет все так же `mutable` коллекция, и именование полей кортежей.

2017-11-11 15:44 UTC, lesya-tishencko commented on src/main/scala/ru/sbau/jvm/scala/MultiSet.scala
> +package ru.spbau.jvm.scala
Опечатка. Исправила

2017-11-11 15:44 UTC, lesya-tishencko commented on src/main/scala/ru/sbau/jvm/scala/MultiSet.scala
> +class MultiSet[A](private var map: Map[A, Int] = Map.empty[A, Int]) {
2. Обязательно, иначе не компилируется метод flatMap, так как считает параметр = Nothing
Явное указание параметров помогает указать компилятору так не делать
1. Поменяла имя 3. Добавила (пыталась просто за бесплатно получить это с помощью case класса, но тогда проблемы в companion-object)

2017-11-11 15:44 UTC, lesya-tishencko commented on src/main/scala/ru/sbau/jvm/scala/MultiSet.scala
> +  def +(elem: A): Unit = this.map = this.map + (elem -> (this.map.getOrElse(elem, 0) + 1))
Исправила

2017-11-11 15:44 UTC, lesya-tishencko commented on src/main/scala/ru/sbau/jvm/scala/MultiSet.scala
> +  def -(elem: A): Unit = this.map.get(elem) match {
Ну, немного меньше места занимает... Я исправила на element

2017-11-11 15:44 UTC, lesya-tishencko commented on src/main/scala/ru/sbau/jvm/scala/MultiSet.scala
> +    case None => ()
Убрала

2017-11-11 15:44 UTC, lesya-tishencko commented on src/main/scala/ru/sbau/jvm/scala/MultiSet.scala
> +  def find(elem: A): Option[A] = this.map.get(elem) match {
Я думала его реализовывать обязательно по требованиям к проекту. Я понимаю, что функциональной нагрузки он не несет. Я его убрала

2017-11-11 15:44 UTC, lesya-tishencko commented on src/main/scala/ru/sbau/jvm/scala/MultiSet.scala
> +  def map[B](fun: A => B): MultiSet[B] = new MultiSet(this.map.map(x => (fun(x._1) -> x._2)))
Да, тут ошибка. Я исправила и добавила этот пример в тесты

2017-11-11 15:44 UTC, lesya-tishencko commented on src/main/scala/ru/sbau/jvm/scala/MultiSet.scala
> +    var sumMap = other.map.map(x => (x._1, x._2 + this.map.getOrElse(x._1, 0)))
Исправила

2017-11-11 15:44 UTC, lesya-tishencko commented on src/main/scala/ru/sbau/jvm/scala/MultiSet.scala
> +      case None => (x._1, -1)
Исправила, сократила код метода и вроде бы сделала понятнее

2017-11-11 15:44 UTC, lesya-tishencko commented on src/main/scala/ru/sbau/jvm/scala/MultiSet.scala
> +      case Some(n) => (x._1, min(x._2, n))
Поменяла

2017-11-11 15:44 UTC, lesya-tishencko commented on src/main/scala/ru/sbau/jvm/scala/MultiSet.scala
> +  def apply[A](map: Map[A, Int] = Map.empty): MultiSet[A] = new MultiSet(map)
Упс... Сделала правильно

2017-11-11 15:44 UTC, lesya-tishencko commented on src/main/scala/ru/sbau/jvm/scala/MultiSet.scala
> +    if (arg.map.isEmpty) None else
Как я поняла, надо просто вынести в отдельную переменную?

2017-11-11 15:45 UTC, lesya-tishencko commented on src/main/scala/ru/sbau/jvm/scala/MultiSet.scala
> +      Some(arg.map.foldLeft(Seq.empty[A])((arg, next) => arg ++ Seq.fill(next._2)(next._1)))
Спасибо, поменяла

2017-11-11 15:45 UTC, lesya-tishencko commented on src/test/scala/ru/sbau/jvm/scala/MultiSetTest.scala
> +      case _ => assert(false)
Спасибо, поменяла

2017-11-11 15:45 UTC, lesya-tishencko commented on src/test/scala/ru/sbau/jvm/scala/MultiSetTest.scala
> +    assert(mySet.apply(1) == 1)
1. убрала явный вызов
2. в этой библиотеке таких методов нет. Там только assert, assertResult, assertDoesNotCompile

2017-11-11 15:45 UTC, lesya-tishencko commented on src/test/scala/ru/sbau/jvm/scala/MultiSetTest.scala
> +    assert(!mySet.contains(2))
Комментарий выше

2017-11-11 15:45 UTC, lesya-tishencko commented on src/test/scala/ru/sbau/jvm/scala/MultiSetTest.scala
> +      if (res == Some(20))
Не могу даже вспомнить, что я тут пыталась этим if проверить, но да, он не нужен

2017-11-11 15:45 UTC, lesya-tishencko commented on src/test/scala/ru/sbau/jvm/scala/MultiSetTest.scala
> +    filtred.apply(2) match {
Не могу даже вспомнить, что я тут пыталась этим match проверить, но да, он не нужен

2017-11-11 15:45 UTC, lesya-tishencko commented on src/test/scala/ru/sbau/jvm/scala/MultiSetTest.scala
> +    mySet + 1;
Убрала

2017-11-11 15:45 UTC, lesya-tishencko commented on src/test/scala/ru/sbau/jvm/scala/MultiSetTest.scala
> +    assert(mySet.find("1_one") == Some("1_one"))
См. комментарий к методу find
Теперь тут contains

2017-11-11 15:50 UTC, lesya-tishencko commented
@adkozlov Исправления внесены

2018-01-26 07:39 UTC, closed without merging